package jorn.hiel.mapper.service.enums;

public enum VehicleSpec {

    AIVEHICLE, FILLUNIT, MOTORIZED, ATTACHABLE, BALELOADER, CONNECTIONHOSES, COVER, ENTERABLE, CULTIVATOR, CYLINDERED,
    DASHBOARD, DISCHARGEABLE, DRIVABLE, DYNAMICALLYLOADEDPARTS, FILLVOLUME, FOLDABLE, GROUNDREFERENCE, LIGHTS,
    POWERTAKEOFFS, WIPERS, TURNONVEHICLE, POWERCONSUMER, SPEEDROTATINGPARTS, SPRAYER,
    SUSPENSIONS, TRAILER, WHEELS, WOODHARVESTER, WORKAREA, BASEMATERIAL, TIPOCCLUDER, FOLIAGEBENDING, WASHABLE, WEARABLE, BUNKERSILOCOMPACTER,
    HONK, ANIMATEDVEHICLE, MOUNTABLE, IKCHAINS , CRAWLERS, SLOPECOMPENSATION, AIIMPLEMENT, ARTICULATEDAXIS
    ,ATTACHERJOINTS, FRONTLOADERATTACHER, CYLINDEREDFOLDABLE, TENSIONBELTS, DYNAMICMOUNTATTACHER, PIPE,
    BUNKERSILOINTERACTOR, RECEIVINGHOPPER, MIXERWAGON, CONVEYORBELT, BALEGRAB, SEMITRAILERFRONT, LIVESTOCKTRAILER,
    WORKPARTICLES, ATTACHERJOINTCONTROL, SHOVEL, JIGGLINGPARTS, COMBINE, CUTTER, AICONVEYORBELT, BALEWRAPPER,
    CRABSTEERING, REVERSEDRIVING, SPLINEVEHICLE, LOGGRAB, WOODCRUSHER, PICKUP, HOOKLIFTCONTAINER, RANDOMLYMOVINGPARTS,
    FRUITPREPARER, MOWER, LEVELER, ROPES, STUMPCUTTER,FORAGEWAGON,WINDROWER,GROUNDADJUSTEDNODES,RIDGEMARKER,
    WORKMODE, ROLLER, TEDDER, MANUREBARREL, TREESAW, WEEDER, WATERTRAILER,FILLTRIGGERVEHICLE,HOOKLIFTTRAILER,
    BUYABLEBALE,LOCOMOTIVE,SOWINGMACHINE,BALER,FERTILIZINGCULTIVATOR, TENSIONBELTOBJECT, FERTILIZINGSOWINGMACHINE,
    PLOW,CCTDRIVABLE, RIDEABLE, TREEPLANTER, STRAWBLOWER




    ;

}
