package jorn.hiel.mapper.service.enums;

public enum VehicleSpec {

    AI, FILLUNIT, MOTORIZED, ATTACHABLE, BALELOADER, CONNECTIONHOSES, COVER, ENTERABLE, CULTIVATOR, CYLINDERED,
    DASHBOARD, DISCHARGEABLE, DRIVABLE, DYNAMICALLYLOADEDPARTS, FILLVOLUME, FOLDABLE, GROUNDREFERENCE, LIGHTS,
    BASEMATERIALCONFIGURATION, POWERTAKEOFFS, WIPERS, TURNONVEHICLE, POWERCONSUMER, SPEEDROTATINGPARTS, SPRAYER,
    SUSPENSIONS, TRAILER, WHEELS, WOODHARVESTER, WORKAREAS;

}
